// Auth.
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

// Profile.
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

// Task.
export const GET_DEFAULT_TASKS = 'GET_DEFAULT_TASKS';
export const ADD_NEW_DEFAULT_TASK = 'ADD_NEW_DEFAULT_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const SET_CURRENT_EDITED_TASK = 'SET_CURRENT_EDITED_TASK';
export const CLEAR_CURRENT_EDITED_TASK = 'CLEAR_CURRENT_EDITED_TASK';
export const ADD_NEW_TASK_PLACEHOLDER = 'ADD_NEW_TASK_PLACEHOLDER';
export const REMOVE_TASK_PLACEHOLDER = 'REMOVE_TASK_PLACEHOLDER';
