name: CI

on:
  push:
    branches:
      - master
      - gh-actions

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test
        env:
          CI: true
          MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          MAILER_EMAIL_ID: ${{ secrets.MAILER_EMAIL_ID }}
          MAILER_EMAIL_PASSWORD: ${{ secrets.MAILER_EMAIL_PASSWORD }}
          MAILER_SERVICE_PROVIDER: ${{ secrets.MAILER_SERVICE_PROVIDER }}

      - name: Run build command if exists
        run: |
          npm run build --if-present

      - name: Add remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:master -f
